tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew install "autoconf"
brew install "asdf"
brew install "awscli"
brew install "glib"
brew install "erlang"
brew install "elixir"
brew install "geos"
brew install "libxml2"
brew install "libdap"
brew install "libpq"
brew install "libspatialite"
brew install "gdal"
brew install "git"
brew install "httpie"
brew install "kubernetes-cli"
brew install "postgresql", restart_service: true
brew install "postgis"
brew install "rbenv"
brew install "ruby-build"
brew install "redis", restart_service: true
brew install "yarn"
cask install "ngrok"
brew install "thefuck"
