brew "autoconf"
brew "asdf"
brew "awscli"
brew "glib"
brew "erlang"
brew "elixir"
brew "geos"
brew "libxml2"
brew "libdap"
brew "libpq"
brew "libspatialite"
brew "gdal"
brew "git"
brew "httpie"
brew "kubernetes-cli"
brew "postgresql", restart_service: true
brew "postgis"
brew "rbenv"
brew "ruby-build"
brew "redis", restart_service: true
brew "yarn"
cask "ngrok"
brew "thefuck"
